// 200 Blog Konusu - Kategorilere göre düzenlenmiş
// Bu dosya sadece planlama içindir, _registry.ts'e aktarılacak

export const topics = [
  // === SEO (30 konu) ===
  { slug: "seo-nedir-baslangic-rehberi", title: "SEO Nedir? Yeni Başlayanlar İçin Kapsamlı Rehber", category: "SEO" },
  { slug: "teknik-seo-kontrol-listesi", title: "Teknik SEO Kontrol Listesi: 50+ Maddelik Denetim Rehberi", category: "SEO" },
  { slug: "on-page-seo-optimizasyonu", title: "On-Page SEO Optimizasyonu: Adım Adım Uygulama Kılavuzu", category: "SEO" },
  { slug: "off-page-seo-backlink-stratejileri", title: "Off-Page SEO ve Backlink Stratejileri: 2026 Güncel Rehber", category: "SEO" },
  { slug: "yerel-seo-rehberi", title: "Yerel SEO Rehberi: Google Haritalar'da Üst Sıralara Çıkma", category: "SEO" },
  { slug: "anahtar-kelime-arastirmasi", title: "Anahtar Kelime Araştırması Nasıl Yapılır? Adım Adım Kılavuz", category: "SEO" },
  { slug: "google-search-console-rehberi", title: "Google Search Console Kullanım Rehberi: A'dan Z'ye", category: "SEO" },
  { slug: "site-hizi-optimizasyonu", title: "Site Hızı Optimizasyonu: Core Web Vitals İyileştirme Rehberi", category: "SEO" },
  { slug: "mobil-seo-optimizasyonu", title: "Mobil SEO Optimizasyonu: Mobile-First Indexing Rehberi", category: "SEO" },
  { slug: "e-ticaret-seo-rehberi", title: "E-Ticaret SEO Rehberi: Online Mağazanızı Optimize Edin", category: "SEO" },
  { slug: "seo-icin-icerik-yazimi", title: "SEO İçin İçerik Yazımı: Arama Motorlarının Sevdiği İçerikler", category: "SEO" },
  { slug: "schema-markup-rehberi", title: "Schema Markup Rehberi: Yapısal Veri Uygulaması", category: "SEO" },
  { slug: "canonical-url-nedir", title: "Canonical URL Nedir? Duplicate Content Sorununu Çözme", category: "SEO" },
  { slug: "xml-sitemap-olusturma", title: "XML Sitemap Oluşturma ve Optimize Etme Rehberi", category: "SEO" },
  { slug: "robots-txt-rehberi", title: "Robots.txt Dosyası: Yazım Kuralları ve Örnekler", category: "SEO" },
  { slug: "seo-audit-nasil-yapilir", title: "SEO Audit Nasıl Yapılır? Kapsamlı Site Denetim Rehberi", category: "SEO" },
  { slug: "google-algoritma-guncellemeleri", title: "Google Algoritma Güncellemeleri: Tarihçe ve Etkileri", category: "SEO" },
  { slug: "link-building-teknikleri", title: "Link Building Teknikleri: Kaliteli Backlink Kazanma Yolları", category: "SEO" },
  { slug: "seo-raporlama-metrikleri", title: "SEO Raporlama ve Metrikleri: Neyi Ölçmelisiniz?", category: "SEO" },
  { slug: "hreflang-etiketi-rehberi", title: "Hreflang Etiketi Rehberi: Çok Dilli Siteler İçin SEO", category: "SEO" },
  { slug: "sayfa-hizi-ve-seo-iliskisi", title: "Sayfa Hızı ve SEO İlişkisi: Performans Optimizasyon Teknikleri", category: "SEO" },
  { slug: "seo-icin-gorsel-optimizasyonu", title: "SEO İçin Görsel Optimizasyonu: Alt Text, Boyut ve Format", category: "SEO" },
  { slug: "featured-snippet-kazanma", title: "Featured Snippet Nasıl Kazanılır? Sıfır Pozisyon Rehberi", category: "SEO" },
  { slug: "crawl-budget-optimizasyonu", title: "Crawl Budget Optimizasyonu: Tarama Bütçesini Verimli Kullanma", category: "SEO" },
  { slug: "internal-linking-stratejisi", title: "Internal Linking Stratejisi: Dahili Bağlantı Rehberi", category: "SEO" },
  { slug: "seo-icin-url-yapisi", title: "SEO İçin URL Yapısı: En İyi Uygulamalar ve Örnekler", category: "SEO" },
  { slug: "e-e-a-t-nedir", title: "E-E-A-T Nedir? Google'ın Güvenilirlik Kriterleri Rehberi", category: "SEO" },
  { slug: "seo-ve-yapay-zeka", title: "SEO ve Yapay Zeka: AI Araçları ile SEO Optimizasyonu", category: "SEO" },
  { slug: "negatif-seo-nedir-korunma", title: "Negatif SEO Nedir? Korunma ve Müdahale Rehberi", category: "SEO" },
  { slug: "seo-icin-log-analizi", title: "SEO İçin Log Analizi: Sunucu Kayıtlarından Veri Çıkarma", category: "SEO" },

  // === SEM & Google Ads (25 konu) ===
  { slug: "google-ads-baslangic-rehberi", title: "Google Ads Başlangıç Rehberi: İlk Kampanyanızı Oluşturun", category: "SEM" },
  { slug: "google-ads-kalite-puani", title: "Google Ads Kalite Puanı: Artırma Teknikleri ve Stratejiler", category: "SEM" },
  { slug: "arama-aglari-kampanyasi", title: "Arama Ağları Kampanyası: Kurulum ve Optimizasyon Rehberi", category: "SEM" },
  { slug: "goruntulu-reklam-aglari", title: "Görüntülü Reklam Ağları (Display): Strateji ve Hedefleme", category: "SEM" },
  { slug: "youtube-reklam-rehberi", title: "YouTube Reklam Rehberi: Video Kampanya Türleri ve Stratejiler", category: "SEM" },
  { slug: "google-shopping-reklam", title: "Google Shopping Reklamları: E-Ticaret İçin Kurulum Rehberi", category: "SEM" },
  { slug: "remarketing-retargeting-rehberi", title: "Remarketing ve Retargeting Rehberi: Yeniden Hedefleme Stratejileri", category: "SEM" },
  { slug: "google-ads-donusum-takibi", title: "Google Ads Dönüşüm Takibi: Kurulum ve Optimizasyon", category: "SEM" },
  { slug: "reklam-metni-yazma-teknikleri", title: "Reklam Metni Yazma Teknikleri: Tıklama Oranını Artırın", category: "SEM" },
  { slug: "google-ads-butce-yonetimi", title: "Google Ads Bütçe Yönetimi: Maliyet Optimizasyon Rehberi", category: "SEM" },
  { slug: "ppc-reklam-metrikleri", title: "PPC Reklam Metrikleri: CPC, CTR, ROAS ve Daha Fazlası", category: "SEM" },
  { slug: "google-ads-ab-testi", title: "Google Ads A/B Testi: Reklam Performansını Test Etme Rehberi", category: "SEM" },
  { slug: "negatif-anahtar-kelime", title: "Negatif Anahtar Kelime Stratejisi: Bütçe Tasarrufu Rehberi", category: "SEM" },
  { slug: "landing-page-optimizasyonu", title: "Landing Page Optimizasyonu: Dönüşüm Oranını Artırma Rehberi", category: "SEM" },
  { slug: "google-ads-uzantilari", title: "Google Ads Uzantıları: Tüm Uzantı Türleri ve Kullanımı", category: "SEM" },
  { slug: "bing-ads-rehberi", title: "Microsoft Ads (Bing) Rehberi: Google Ads'e Alternatif", category: "SEM" },
  { slug: "pmax-kampanya-rehberi", title: "Performance Max Kampanyaları: Kurulum ve Optimizasyon Rehberi", category: "SEM" },
  { slug: "google-ads-hedefleme-secenekleri", title: "Google Ads Hedefleme Seçenekleri: Doğru Kitleye Ulaşma", category: "SEM" },
  { slug: "sem-raporlama-dashboard", title: "SEM Raporlama ve Dashboard Oluşturma Rehberi", category: "SEM" },
  { slug: "google-ads-otomatik-teklifler", title: "Google Ads Otomatik Teklif Stratejileri: Hangisini Seçmeli?", category: "SEM" },
  { slug: "arama-terimi-raporu-analizi", title: "Arama Terimi Raporu Analizi: Gereksiz Harcamaları Azaltma", category: "SEM" },
  { slug: "responsive-arama-reklamlari", title: "Responsive Arama Reklamları (RSA): En İyi Uygulamalar", category: "SEM" },
  { slug: "google-ads-hesap-yapisi", title: "Google Ads Hesap Yapısı: Kampanya Organizasyonu Rehberi", category: "SEM" },
  { slug: "sem-seo-birlikte-kullanma", title: "SEM ve SEO Birlikte Kullanma: Entegre Strateji Rehberi", category: "SEM" },
  { slug: "google-ads-akilli-kampanyalar", title: "Google Ads Akıllı Kampanyalar: Küçük İşletmeler İçin Rehber", category: "SEM" },

  // === Sosyal Medya Pazarlama (20 konu) ===
  { slug: "instagram-reklam-rehberi", title: "Instagram Reklam Rehberi: Kampanya Türleri ve Stratejiler", category: "Sosyal Medya" },
  { slug: "facebook-ads-hedefleme", title: "Facebook Ads Hedefleme: Özel ve Benzer Kitleler Rehberi", category: "Sosyal Medya" },
  { slug: "tiktok-reklam-rehberi", title: "TikTok Reklam Rehberi: Kısa Video Pazarlama Stratejileri", category: "Sosyal Medya" },
  { slug: "linkedin-reklam-b2b", title: "LinkedIn Reklam Rehberi: B2B Pazarlama Stratejileri", category: "Sosyal Medya" },
  { slug: "sosyal-medya-icerik-takvimi", title: "Sosyal Medya İçerik Takvimi: Planlama ve Uygulama Rehberi", category: "Sosyal Medya" },
  { slug: "influencer-marketing-rehberi", title: "Influencer Marketing Rehberi: Doğru İş Birliği Stratejileri", category: "Sosyal Medya" },
  { slug: "sosyal-medya-analitik", title: "Sosyal Medya Analitik: Ölçümleme ve Raporlama Rehberi", category: "Sosyal Medya" },
  { slug: "video-pazarlama-stratejileri", title: "Video Pazarlama Stratejileri: İçerik Üretim Rehberi", category: "Sosyal Medya" },
  { slug: "sosyal-medya-kriz-yonetimi", title: "Sosyal Medya Kriz Yönetimi: Adım Adım Müdahale Planı", category: "Sosyal Medya" },
  { slug: "pinterest-pazarlama-rehberi", title: "Pinterest Pazarlama Rehberi: Görsel Arama Optimizasyonu", category: "Sosyal Medya" },
  { slug: "twitter-x-reklam-rehberi", title: "X (Twitter) Reklam Rehberi: Kampanya Türleri ve İpuçları", category: "Sosyal Medya" },
  { slug: "whatsapp-business-pazarlama", title: "WhatsApp Business Pazarlama: Müşteri İletişim Rehberi", category: "Sosyal Medya" },
  { slug: "ugc-kullanici-icerigi", title: "UGC (Kullanıcı İçeriği) Stratejisi: Topluluk Oluşturma Rehberi", category: "Sosyal Medya" },
  { slug: "sosyal-medya-reklam-butcesi", title: "Sosyal Medya Reklam Bütçesi: Platform Bazlı Planlama Rehberi", category: "Sosyal Medya" },
  { slug: "facebook-pixel-kurulumu", title: "Facebook Pixel Kurulumu ve Kullanımı: Kapsamlı Rehber", category: "Sosyal Medya" },
  { slug: "instagram-organik-buyume", title: "Instagram Organik Büyüme Stratejileri: 2026 Rehberi", category: "Sosyal Medya" },
  { slug: "sosyal-medya-topluluk-yonetimi", title: "Sosyal Medya Topluluk Yönetimi: Etkileşim Artırma Rehberi", category: "Sosyal Medya" },
  { slug: "snapchat-reklam-rehberi", title: "Snapchat Reklam Rehberi: Genç Kitleye Ulaşma Stratejileri", category: "Sosyal Medya" },
  { slug: "sosyal-medya-otomasyon-araclari", title: "Sosyal Medya Otomasyon Araçları: Karşılaştırma ve Rehber", category: "Sosyal Medya" },
  { slug: "canli-yayin-pazarlama", title: "Canlı Yayın Pazarlama: Live Commerce ve Strateji Rehberi", category: "Sosyal Medya" },

  // === E-Ticaret (20 konu) ===
  { slug: "e-ticaret-sitesi-kurma-rehberi", title: "E-Ticaret Sitesi Kurma Rehberi: Platform Seçimi ve Kurulum", category: "E-Ticaret" },
  { slug: "trendyol-magaza-acma", title: "Trendyol Mağaza Açma Rehberi: Adım Adım Kayıt ve Satış", category: "E-Ticaret" },
  { slug: "hepsiburada-magaza-yonetimi", title: "Hepsiburada Mağaza Yönetimi: Satıcı Paneli Rehberi", category: "E-Ticaret" },
  { slug: "amazon-turkiye-satis-rehberi", title: "Amazon Türkiye Satış Rehberi: FBA ve Ürün Listeleme", category: "E-Ticaret" },
  { slug: "urun-sayfasi-optimizasyonu", title: "Ürün Sayfası Optimizasyonu: Dönüşüm Artırma Teknikleri", category: "E-Ticaret" },
  { slug: "sepet-terk-orani-dusurme", title: "Sepet Terk Oranını Düşürme: 15 Kanıtlanmış Strateji", category: "E-Ticaret" },
  { slug: "e-ticaret-fotograf-cekim", title: "E-Ticaret Ürün Fotoğrafçılığı: Profesyonel Çekim Rehberi", category: "E-Ticaret" },
  { slug: "odeme-sistemleri-entegrasyonu", title: "Ödeme Sistemleri Entegrasyonu: iyzico, PayTR, Stripe Rehberi", category: "E-Ticaret" },
  { slug: "kargo-ve-lojistik-yonetimi", title: "E-Ticaret Kargo ve Lojistik Yönetimi: Optimizasyon Rehberi", category: "E-Ticaret" },
  { slug: "e-ticaret-musteri-sadakati", title: "E-Ticaret Müşteri Sadakati: Retention Stratejileri Rehberi", category: "E-Ticaret" },
  { slug: "stok-yonetimi-rehberi", title: "E-Ticaret Stok Yönetimi: Envanter Optimizasyon Rehberi", category: "E-Ticaret" },
  { slug: "cross-border-e-ticaret", title: "Sınır Ötesi E-Ticaret: Global Satış Rehberi", category: "E-Ticaret" },
  { slug: "e-ticaret-email-pazarlama", title: "E-Ticaret E-posta Pazarlama: Otomasyon ve Segmentasyon", category: "E-Ticaret" },
  { slug: "shopify-turkiye-rehberi", title: "Shopify Türkiye Rehberi: Mağaza Kurulumu ve Yönetimi", category: "E-Ticaret" },
  { slug: "woocommerce-optimizasyonu", title: "WooCommerce Optimizasyonu: Performans ve SEO Rehberi", category: "E-Ticaret" },
  { slug: "pazaryeri-entegrasyonu", title: "Pazaryeri Entegrasyonu: Çok Kanallı Satış Yönetimi Rehberi", category: "E-Ticaret" },
  { slug: "dropshipping-turkiye-rehberi", title: "Dropshipping Türkiye Rehberi: Başlangıç ve Strateji", category: "E-Ticaret" },
  { slug: "e-ticaret-fiyatlandirma-stratejisi", title: "E-Ticaret Fiyatlandırma Stratejisi: Dinamik Fiyatlama Rehberi", category: "E-Ticaret" },
  { slug: "musteriye-yorum-yonetimi", title: "Müşteri Yorum Yönetimi: Değerlendirme Stratejileri Rehberi", category: "E-Ticaret" },
  { slug: "e-ticaret-hukuki-gereklilikler", title: "E-Ticaret Hukuki Gereklilikler: Yasal Uyumluluk Rehberi", category: "E-Ticaret" },

  // === Dijital Pazarlama Genel (20 konu) ===
  { slug: "dijital-pazarlama-stratejisi", title: "Dijital Pazarlama Stratejisi Oluşturma: Kapsamlı Rehber", category: "Dijital Pazarlama" },
  { slug: "icerik-pazarlama-rehberi", title: "İçerik Pazarlama Rehberi: Strateji, Üretim ve Dağıtım", category: "Dijital Pazarlama" },
  { slug: "email-pazarlama-rehberi", title: "E-posta Pazarlama Rehberi: Otomasyon ve Dönüşüm", category: "Dijital Pazarlama" },
  { slug: "donusum-orani-optimizasyonu-cro", title: "Dönüşüm Oranı Optimizasyonu (CRO): A/B Test Rehberi", category: "Dijital Pazarlama" },
  { slug: "musteri-yolculugu-haritalama", title: "Müşteri Yolculuğu Haritalama: Customer Journey Map Rehberi", category: "Dijital Pazarlama" },
  { slug: "dijital-pazarlama-butcesi", title: "Dijital Pazarlama Bütçesi Planlama: Kanal Dağılımı Rehberi", category: "Dijital Pazarlama" },
  { slug: "affiliate-marketing-rehberi", title: "Affiliate Marketing Rehberi: Gelir Ortaklığı Başlangıç Kılavuzu", category: "Dijital Pazarlama" },
  { slug: "podcast-pazarlama-rehberi", title: "Podcast Pazarlama Rehberi: Sesli İçerik Stratejileri", category: "Dijital Pazarlama" },
  { slug: "growth-hacking-teknikleri", title: "Growth Hacking Teknikleri: Hızlı Büyüme Stratejileri Rehberi", category: "Dijital Pazarlama" },
  { slug: "ab-testi-rehberi", title: "A/B Testi Rehberi: Hipotez, Uygulama ve Analiz", category: "Dijital Pazarlama" },
  { slug: "marketing-funnel-rehberi", title: "Pazarlama Hunisi (Funnel) Rehberi: TOFU, MOFU, BOFU", category: "Dijital Pazarlama" },
  { slug: "marka-bilinirligini-artirma", title: "Marka Bilinirliğini Artırma: Dijital Strateji Rehberi", category: "Dijital Pazarlama" },
  { slug: "inbound-marketing-rehberi", title: "Inbound Marketing Rehberi: Gelen Pazarlama Stratejileri", category: "Dijital Pazarlama" },
  { slug: "marketing-otomasyonu", title: "Marketing Otomasyonu: Araç Seçimi ve Kurulum Rehberi", category: "Dijital Pazarlama" },
  { slug: "lead-generation-stratejileri", title: "Lead Generation Stratejileri: Potansiyel Müşteri Kazanma", category: "Dijital Pazarlama" },
  { slug: "crm-secimi-ve-kurulumu", title: "CRM Seçimi ve Kurulumu: İşletmeler İçin Karşılaştırma Rehberi", category: "Dijital Pazarlama" },
  { slug: "copywriting-teknikleri", title: "Copywriting Teknikleri: Satış Odaklı İçerik Yazma Rehberi", category: "Dijital Pazarlama" },
  { slug: "webinar-pazarlama-rehberi", title: "Webinar Pazarlama Rehberi: Online Etkinlik Stratejileri", category: "Dijital Pazarlama" },
  { slug: "kullanici-deneyimi-tasarimi", title: "Kullanıcı Deneyimi (UX) Tasarımı: Temel İlkeler Rehberi", category: "Dijital Pazarlama" },
  { slug: "dijital-pr-rehberi", title: "Dijital PR Rehberi: Online İtibar Yönetimi Stratejileri", category: "Dijital Pazarlama" },

  // === Web Geliştirme ve Tasarım (25 konu) ===
  { slug: "nextjs-baslangic-rehberi", title: "Next.js Başlangıç Rehberi: Modern Web Geliştirme", category: "Web Geliştirme" },
  { slug: "responsive-web-tasarim", title: "Responsive Web Tasarım: Mobil Uyumlu Site Oluşturma Rehberi", category: "Web Geliştirme" },
  { slug: "web-performans-optimizasyonu", title: "Web Performans Optimizasyonu: Lighthouse 100 Puan Rehberi", category: "Web Geliştirme" },
  { slug: "web-erisilebilirlik-wcag", title: "Web Erişilebilirlik (WCAG 2.2): Kapsamlı Uygulama Rehberi", category: "Web Geliştirme" },
  { slug: "tailwindcss-rehberi", title: "Tailwind CSS Rehberi: Utility-First CSS ile Hızlı Geliştirme", category: "Web Geliştirme" },
  { slug: "typescript-baslangic-rehberi", title: "TypeScript Başlangıç Rehberi: Tip Güvenli JavaScript", category: "Web Geliştirme" },
  { slug: "react-performans-optimizasyonu", title: "React Performans Optimizasyonu: Memo, Lazy ve Suspense", category: "Web Geliştirme" },
  { slug: "pwa-progressive-web-app", title: "PWA (Progressive Web App) Geliştirme Rehberi", category: "Web Geliştirme" },
  { slug: "web-guvenlik-temelleri", title: "Web Güvenlik Temelleri: OWASP Top 10 ve Korunma Rehberi", category: "Web Geliştirme" },
  { slug: "api-tasarim-rehberi", title: "REST API Tasarım Rehberi: En İyi Uygulamalar", category: "Web Geliştirme" },
  { slug: "git-versiyon-kontrol-rehberi", title: "Git Versiyon Kontrol Rehberi: Başlangıçtan İleri Seviyeye", category: "Web Geliştirme" },
  { slug: "cicd-pipeline-rehberi", title: "CI/CD Pipeline Rehberi: GitHub Actions ile Otomasyon", category: "Web Geliştirme" },
  { slug: "vercel-deployment-rehberi", title: "Vercel Deployment Rehberi: Next.js Projelerini Yayınlama", category: "Web Geliştirme" },
  { slug: "dark-mode-uygulama-rehberi", title: "Dark Mode Uygulama Rehberi: Tema Sistemi Oluşturma", category: "Web Geliştirme" },
  { slug: "web-animasyon-rehberi", title: "Web Animasyon Rehberi: CSS, Framer Motion ve GSAP", category: "Web Geliştirme" },
  { slug: "headless-cms-karsilastirmasi", title: "Headless CMS Karşılaştırması: Strapi, Sanity, Contentful", category: "Web Geliştirme" },
  { slug: "jamstack-mimari-rehberi", title: "Jamstack Mimari Rehberi: Modern Web Geliştirme Yaklaşımı", category: "Web Geliştirme" },
  { slug: "web-font-optimizasyonu", title: "Web Font Optimizasyonu: Performans ve Tipografi Rehberi", category: "Web Geliştirme" },
  { slug: "lazy-loading-rehberi", title: "Lazy Loading Rehberi: Görsel ve Bileşen Gecikmeli Yükleme", category: "Web Geliştirme" },
  { slug: "svg-optimizasyonu", title: "SVG Optimizasyonu ve Animasyonu: Web Grafik Rehberi", category: "Web Geliştirme" },
  { slug: "docker-web-gelistirme", title: "Docker ile Web Geliştirme: Konteyner Ortamı Rehberi", category: "Web Geliştirme" },
  { slug: "graphql-baslangic-rehberi", title: "GraphQL Başlangıç Rehberi: REST API'ye Alternatif", category: "Web Geliştirme" },
  { slug: "i18n-coklu-dil-rehberi", title: "Çoklu Dil (i18n) Desteği Rehberi: Next.js ile Uygulama", category: "Web Geliştirme" },
  { slug: "website-migration-rehberi", title: "Website Migration Rehberi: SEO Kaybetmeden Taşıma", category: "Web Geliştirme" },
  { slug: "web-hosting-karsilastirmasi", title: "Web Hosting Karşılaştırması: Vercel, Netlify, AWS, Cloudflare", category: "Web Geliştirme" },

  // === Analitik ve Veri (20 konu) ===
  { slug: "google-analytics-4-rehberi", title: "Google Analytics 4 (GA4) Rehberi: Kurulum ve Kullanım", category: "Analitik" },
  { slug: "google-tag-manager-rehberi", title: "Google Tag Manager Rehberi: Etiket Yönetimi Kılavuzu", category: "Analitik" },
  { slug: "veri-odakli-pazarlama", title: "Veri Odaklı Pazarlama: Data-Driven Marketing Rehberi", category: "Analitik" },
  { slug: "ga4-etkinlik-izleme", title: "GA4 Etkinlik İzleme: Custom Events ve Dönüşüm Kurulumu", category: "Analitik" },
  { slug: "utm-parametreleri-rehberi", title: "UTM Parametreleri Rehberi: Kampanya Takibi ve Analiz", category: "Analitik" },
  { slug: "heatmap-ve-session-recording", title: "Heatmap ve Session Recording: Kullanıcı Davranış Analizi", category: "Analitik" },
  { slug: "kohort-analizi-rehberi", title: "Kohort Analizi Rehberi: Kullanıcı Segmentasyonu", category: "Analitik" },
  { slug: "attribution-modelleri", title: "Attribution Modelleri: Dönüşüm İlişkilendirme Rehberi", category: "Analitik" },
  { slug: "google-looker-studio-rehberi", title: "Google Looker Studio Rehberi: Dashboard Oluşturma Kılavuzu", category: "Analitik" },
  { slug: "web-analitik-metrikleri", title: "Web Analitik Metrikleri: Bounce Rate, Session, Pageview", category: "Analitik" },
  { slug: "ga4-audience-olusturma", title: "GA4 Audience Oluşturma: Hedef Kitle Segmentasyonu Rehberi", category: "Analitik" },
  { slug: "server-side-tracking", title: "Server-Side Tracking: Sunucu Taraflı Takip Rehberi", category: "Analitik" },
  { slug: "consent-mode-v2-rehberi", title: "Google Consent Mode v2 Rehberi: KVKK Uyumlu Takip", category: "Analitik" },
  { slug: "e-ticaret-analitik", title: "E-Ticaret Analitik Rehberi: Satış Verisi Analizi", category: "Analitik" },
  { slug: "predictive-analytics-rehberi", title: "Predictive Analytics Rehberi: Tahminsel Analiz Yöntemleri", category: "Analitik" },
  { slug: "ab-testi-istatistik-rehberi", title: "A/B Testi İstatistik Rehberi: Anlamlılık ve Güven Aralığı", category: "Analitik" },
  { slug: "customer-lifetime-value", title: "Customer Lifetime Value (CLV): Hesaplama ve Optimizasyon", category: "Analitik" },
  { slug: "funnel-analizi-rehberi", title: "Funnel Analizi Rehberi: Dönüşüm Hunisi Optimizasyonu", category: "Analitik" },
  { slug: "sosyal-medya-roi-hesaplama", title: "Sosyal Medya ROI Hesaplama: Yatırım Getirisi Analizi", category: "Analitik" },
  { slug: "veri-gorsellestirme-rehberi", title: "Veri Görselleştirme Rehberi: Grafik Türleri ve Araçlar", category: "Analitik" },

  // === AI ve Yapay Zeka (20 konu) ===
  { slug: "yapay-zeka-pazarlama-rehberi", title: "Yapay Zeka ile Pazarlama: AI Marketing Rehberi", category: "Yapay Zeka" },
  { slug: "chatgpt-isletmeler-icin", title: "ChatGPT İşletmeler İçin: Verimlilik Artırma Rehberi", category: "Yapay Zeka" },
  { slug: "ai-icerik-uretimi-rehberi", title: "AI İçerik Üretimi: Yapay Zeka ile İçerik Oluşturma Rehberi", category: "Yapay Zeka" },
  { slug: "ai-gorsel-uretimi", title: "AI Görsel Üretimi: Midjourney, DALL-E ve Araçlar Rehberi", category: "Yapay Zeka" },
  { slug: "ai-chatbot-kurulumu", title: "AI Chatbot Kurulumu: Müşteri Hizmeti Otomasyonu Rehberi", category: "Yapay Zeka" },
  { slug: "prompt-engineering-rehberi", title: "Prompt Engineering Rehberi: Etkili AI Komut Yazma", category: "Yapay Zeka" },
  { slug: "ai-reklam-optimizasyonu", title: "AI Reklam Optimizasyonu: Yapay Zeka ile Kampanya Yönetimi", category: "Yapay Zeka" },
  { slug: "ai-seo-araclari", title: "AI SEO Araçları: Yapay Zeka Destekli SEO Optimizasyonu", category: "Yapay Zeka" },
  { slug: "ai-email-kisisellestirme", title: "AI ile E-posta Kişiselleştirme: Akıllı Segmentasyon Rehberi", category: "Yapay Zeka" },
  { slug: "llmo-optimizasyonu", title: "LLMO (LLM Optimizasyonu): AI Arama Motorları İçin SEO", category: "Yapay Zeka" },
  { slug: "generative-engine-optimization", title: "Generative Engine Optimization (GEO): AI Görünürlük Rehberi", category: "Yapay Zeka" },
  { slug: "ai-video-uretimi-rehberi", title: "AI Video Üretimi Rehberi: Sora, Runway ve Diğer Araçlar", category: "Yapay Zeka" },
  { slug: "ai-musteri-segmentasyonu", title: "AI ile Müşteri Segmentasyonu: Veri Odaklı Hedefleme", category: "Yapay Zeka" },
  { slug: "ai-fiyatlandirma-rehberi", title: "AI Fiyatlandırma: Dinamik Fiyat Optimizasyonu Rehberi", category: "Yapay Zeka" },
  { slug: "ai-sosyal-medya-yonetimi", title: "AI ile Sosyal Medya Yönetimi: Otomasyon Araçları Rehberi", category: "Yapay Zeka" },
  { slug: "ai-veri-analizi-rehberi", title: "AI ile Veri Analizi: İşletmeler İçin Pratik Rehber", category: "Yapay Zeka" },
  { slug: "llms-txt-rehberi", title: "llms.txt Dosyası: AI Botları İçin Web Sitesi Optimizasyonu", category: "Yapay Zeka" },
  { slug: "ai-crm-entegrasyonu", title: "AI CRM Entegrasyonu: Akıllı Müşteri İlişkileri Yönetimi", category: "Yapay Zeka" },
  { slug: "ai-tahminsel-pazarlama", title: "AI Tahminsel Pazarlama: Predictive Marketing Rehberi", category: "Yapay Zeka" },
  { slug: "yapay-zeka-etik-rehberi", title: "Yapay Zeka ve Etik: Sorumlu AI Kullanımı Rehberi", category: "Yapay Zeka" },

  // === Hukuk ve Uyumluluk (10 konu) ===
  { slug: "kvkk-web-sitesi-uyumluluk", title: "KVKK Web Sitesi Uyumluluk Rehberi: Adım Adım Kılavuz", category: "Hukuk" },
  { slug: "gdpr-turkiye-rehberi", title: "GDPR Türkiye Rehberi: Avrupa Veri Koruma Uyumluluğu", category: "Hukuk" },
  { slug: "cerez-politikasi-olusturma", title: "Çerez Politikası Oluşturma: Cookie Consent Rehberi", category: "Hukuk" },
  { slug: "e-ticaret-yasal-gereklilikler", title: "E-Ticaret Yasal Gereklilikler: Mesafeli Satış Sözleşmesi", category: "Hukuk" },
  { slug: "gizlilik-politikasi-hazirlama", title: "Gizlilik Politikası Hazırlama: Şablon ve Rehber", category: "Hukuk" },
  { slug: "dijital-reklam-mevzuati", title: "Dijital Reklam Mevzuatı: Türkiye'de Yasal Düzenlemeler", category: "Hukuk" },
  { slug: "telif-hakki-dijital-icerik", title: "Telif Hakkı ve Dijital İçerik: Yasal Sorumluluk Rehberi", category: "Hukuk" },
  { slug: "elektronik-ticaret-kanunu", title: "Elektronik Ticaret Kanunu: Yükümlülükler ve Uyumluluk", category: "Hukuk" },
  { slug: "veri-ihlali-bildirim-rehberi", title: "Veri İhlali Bildirim Rehberi: KVKK Kapsamında Süreç", category: "Hukuk" },
  { slug: "aydinlatma-metni-hazirlama", title: "Aydınlatma Metni Hazırlama: KVKK Uyumlu Şablon ve Rehber", category: "Hukuk" },

  // === Marka ve Strateji (15 konu) ===
  { slug: "marka-kimligi-olusturma", title: "Marka Kimliği Oluşturma: Logo, Renk ve Tipografi Rehberi", category: "Marka" },
  { slug: "marka-sesi-tonu-belirleme", title: "Marka Sesi ve Tonu Belirleme: Brand Voice Rehberi", category: "Marka" },
  { slug: "rekabet-analizi-rehberi", title: "Rekabet Analizi Rehberi: Rakip Araştırma Yöntemleri", category: "Marka" },
  { slug: "swot-analizi-rehberi", title: "SWOT Analizi Rehberi: Stratejik Planlama Kılavuzu", category: "Marka" },
  { slug: "hedef-kitle-belirleme", title: "Hedef Kitle Belirleme: Persona Oluşturma Rehberi", category: "Marka" },
  { slug: "unique-selling-proposition", title: "USP (Benzersiz Satış Vaadi): Farklılaşma Stratejisi Rehberi", category: "Marka" },
  { slug: "marka-hikayesi-olusturma", title: "Marka Hikayesi Oluşturma: Storytelling Rehberi", category: "Marka" },
  { slug: "kurumsal-kimlik-tasarimi", title: "Kurumsal Kimlik Tasarımı: Görsel Standartlar Rehberi", category: "Marka" },
  { slug: "marka-konumlandirma", title: "Marka Konumlandırma: Positioning Stratejisi Rehberi", category: "Marka" },
  { slug: "dijital-marka-yonetimi", title: "Dijital Marka Yönetimi: Online Reputation Rehberi", category: "Marka" },
  { slug: "logo-tasarim-rehberi", title: "Logo Tasarım Rehberi: Prensipler ve En İyi Uygulamalar", category: "Marka" },
  { slug: "renk-psikolojisi-pazarlama", title: "Renk Psikolojisi ve Pazarlama: Marka Rengi Seçim Rehberi", category: "Marka" },
  { slug: "marka-sadakati-olusturma", title: "Marka Sadakati Oluşturma: Loyalty Program Rehberi", category: "Marka" },
  { slug: "rebranding-rehberi", title: "Rebranding Rehberi: Marka Yenileme Adımları ve Stratejisi", category: "Marka" },
  { slug: "sosyal-sorumluluk-pazarlama", title: "Sosyal Sorumluluk Pazarlama: Purpose-Driven Marketing", category: "Marka" },

  // === Güvenlik ve Altyapı (15 konu) ===
  { slug: "ssl-sertifikasi-rehberi", title: "SSL Sertifikası Rehberi: HTTPS Kurulumu ve Türleri", category: "Güvenlik" },
  { slug: "web-guvenlik-headerlari", title: "Web Güvenlik Header'ları: CSP, HSTS ve Diğerleri", category: "Güvenlik" },
  { slug: "ddos-saldiri-korunma", title: "DDoS Saldırı Korunma: Web Sitesi Güvenlik Rehberi", category: "Güvenlik" },
  { slug: "wordpress-guvenlik-rehberi", title: "WordPress Güvenlik Rehberi: Sızma Testleri ve Koruma", category: "Güvenlik" },
  { slug: "iki-faktorlu-dogrulama", title: "İki Faktörlü Doğrulama (2FA): Uygulama ve Kurulum Rehberi", category: "Güvenlik" },
  { slug: "cdn-kullanimi-rehberi", title: "CDN Kullanımı Rehberi: Cloudflare, Fastly ve Akamai", category: "Güvenlik" },
  { slug: "dns-yonetimi-rehberi", title: "DNS Yönetimi Rehberi: Kayıt Türleri ve Yapılandırma", category: "Güvenlik" },
  { slug: "backup-yedekleme-stratejisi", title: "Backup ve Yedekleme Stratejisi: Veri Koruma Rehberi", category: "Güvenlik" },
  { slug: "xss-saldiri-onleme", title: "XSS Saldırı Önleme: Cross-Site Scripting Koruma Rehberi", category: "Güvenlik" },
  { slug: "sql-injection-korunma", title: "SQL Injection Korunma: Veritabanı Güvenlik Rehberi", category: "Güvenlik" },
  { slug: "api-guvenlik-rehberi", title: "API Güvenlik Rehberi: Authentication ve Rate Limiting", category: "Güvenlik" },
  { slug: "uptime-monitoring-rehberi", title: "Uptime Monitoring Rehberi: Site İzleme ve Uyarı Sistemleri", category: "Güvenlik" },
  { slug: "web-application-firewall", title: "WAF (Web Application Firewall) Rehberi: Koruma Katmanları", category: "Güvenlik" },
  { slug: "zero-trust-guvenlik-modeli", title: "Zero Trust Güvenlik Modeli: Modern Altyapı Koruması", category: "Güvenlik" },
  { slug: "penetrasyon-testi-rehberi", title: "Penetrasyon Testi Rehberi: Web Uygulaması Güvenlik Denetimi", category: "Güvenlik" },
] as const;
